### ISSUE TITLE
Getting "Unexpected error: Timed out"

### ISSUE THREAD

**Issue by Androz2091** [joaomgcd/JoinDesktop#17]
Hello, I installed Join Desktop on a Mac Mini m1 and I'm getting the following error:
![Capture d’écran 2020-11-25 à 17 04 56](https://user-images.githubusercontent.com/42497995/100252695-727ae080-2f40-11eb-859b-f2d214de1428.png)

**Comment by joaomgcd** [comment]
Hi. Can you please use the Report link at the top to send me an email with the details? Thanks

**Comment by Androz2091** [comment]
All right, it's done

**Comment by joaomgcd** [comment]
Thank you! Can you please let me know when you're getting it? Or does it seem random?

**Comment by Androz2091** [comment]
It appears every time I open the app, after 5-6 seconds

**Comment by joaomgcd** [comment]
Hi. Can you please try again with the latest update and see if that helps?

**Comment by Androz2091** [comment]
It crashes and won't open

**Comment by Androz2091** [comment]
I still have the error

**Comment by joaomgcd** [comment]
Thanks. But the app is able to open now? Could you please right-click the app and show me what the error logs show? Thanks!

**Comment by Androz2091** [comment]
Yes, the app opens.

![Capture d’écran 2021-04-21 à 10 50 58](https://user-images.githubusercontent.com/42497995/115525538-7a407600-a28f-11eb-9912-77ab3ab177e2.png)

**Comment by joaomgcd** [comment]
Thanks. And you're able to see your devices normally in the app? Does anything seem not to work?

**Comment by Androz2091** [comment]
I can see my only other device, yes. Everything is working fine, except the "Files" tab.

**Comment by joaomgcd** [comment]
Ok, just to clarify, you open the app and every single time after a few seconds you get that timeout error?

**Comment by Androz2091** [comment]
Yes, without doing anything, after ~6-7 seconds after I open it.

**Comment by joaomgcd** [comment]
Ok, I think I fixed it :)

Can you please try this version? https://github.com/joaomgcd/JoinDesktop/releases/tag/v0.5.2

Thanks!

**Comment by Androz2091** [comment]
Yes, it works perfectly! 😄 
Thank you so much!
The files tab is still not working but I don't care because I don't use it for the moment

**Comment by joaomgcd** [comment]
Great, thank you! :) I'll try figuring out the files tab! Thanks for testing!

**Comment by skarfie123** [comment]
I am using v0.5.2 and I am getting this exact same error.
![image](https://user-images.githubusercontent.com/50425728/115993348-471d2000-a5ca-11eb-81b7-d444508eb395.png)
Happens soon after starting the app as was described above.

**Comment by joaomgcd** [comment]
Hi. No, this one is ok, thanks. 

Does everything still seemingly work for you?

**Comment by skarfie123** [comment]
yeah im getting notifications, able to view files from my phone, control music. although it doesn't seem to happen *every* time, when it does, it happens soon after starting the app.

**Comment by joaomgcd** [comment]
Thanks. And when it does happen, does it seem random? Or can you find some pattern about it?

**Comment by skarfie123** [comment]
Haven't noticed a pattern but will keep observing.

**Comment by joaomgcd** [comment]
Thank you. I'll keep an eye out for it as well.

**Comment by vaibhav011286** [comment]
Hello @joaomgcd,
I installed latest v0.5.2 but I still having **Unexpected Error: Timed out** issue.

![zScreenshot_2021-06-14_22-51-16](https://user-images.githubusercontent.com/170044/121933047-3172de00-cd63-11eb-9d9a-b1a08f7639de.jpg)

Please, help!

**Comment by joaomgcd** [comment]
Thanks! I actually tried fixing another one of those for the next release. Hopefully it'll work!
