### ISSUE TITLE
SMS issues

### ISSUE THREAD

**Issue by tommyent** [joaomgcd/JoinDesktop#8]
Haven't tried to look at things but I had this from the other day and is still an issue
Trace:
TypeError: Cannot read property 'address' of undefined
at ControlSMSConversation.renderCurrentSmsConversation (file:///Applications/Join%20Desktop.app/Contents/Resources/app.asar/v2/sms/conversation/controlsmsconveration.js:125:89)
at async ControlSMSConversation.setSmsConversation (file:///Applications/Join%20Desktop.app/Contents/Resources/app.asar/v2/sms/conversation/controlsmsconveration.js:89:9)
at async AppHelperSMS.reloadConversationFromNetwork (file:///Applications/Join%20Desktop.app/Contents/Resources/app.asar/v2/sms/apphelpersms.js:153:9)
at async AppHelperSMS.switchToConversation (file:///Applications/Join%20Desktop.app/Contents/Resources/app.asar/v2/sms/apphelpersms.js:148:9)
at async AppHelperSMS.setMode (file:///Applications/Join%20Desktop.app/Contents/Resources/app.asar/v2/sms/apphelpersms.js:77:13)

Also 
![Screen Shot 2020-07-28 at 1 55 09 PM](https://user-images.githubusercontent.com/509970/88703051-38a4e500-d0da-11ea-8e87-835bd5e6420d.jpg)
should be 
![Screen Shot 2020-07-28 at 1 56 03 PM](https://user-images.githubusercontent.com/509970/88703069-3e022f80-d0da-11ea-9925-8cc7e9ed93ae.jpg)

Not sure if this has anything to do with RCS

**Comment by joaomgcd** [comment]
Thanks! Probably an issue with MMS. Haven't had a chance to test those yet (my network makes it hard and expensive to use those). 

Do you get that error every time an MMS is in the conversation?

**Comment by tommyent** [comment]
The undefined address happens with or without MMS the [Urgent!] MESSAGE_SUBJECT is every MMS

**Comment by joaomgcd** [comment]
Ok, think this is fixed. Can you please check?

**Comment by tommyent** [comment]
Images are still missing. There is now no indication of an image at all. 
![Screen Shot 2020-07-30 at 12 46 22 PM](https://user-images.githubusercontent.com/509970/88950666-f22ec200-d262-11ea-9326-aabbcd2eaf68.jpg)

**Comment by joaomgcd** [comment]
Yeah, unfortunately I wasn't able to test images yet solely because I have no way to get MMS on my phone right now :/ Need to find a way to do that soon...

**Comment by tommyent** [comment]
What's the issue with getting MMS on your phone? Is it a service provider issue?

**Comment by joaomgcd** [comment]
Yeah, MMS aren't really used here so I don't even have a way of sending them to myself :/

**Comment by tommyent** [comment]
Well the best I can do is offer to test commits. I thought there were test SMS/MMS gateways that you can use outside your provider so I will take a look. Slowly we are being moved to RCS however for the rest of the world I don't think they care.

**Comment by joaomgcd** [comment]
Yeah... I need to try and replicate the code in the Chrome extension cause that's working. I just don't have a way to test it right now :P
